dist: trusty
language: cpp
script:
  - mkdir build && cd build
  - CXX=$COMPILER cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - cmake --build .
  - ./mc_01

env:
  - BUILD_TYPE=Release COMPILER=g++-4.9
  - BUILD_TYPE=Release COMPILER=g++-5
  - BUILD_TYPE=Release COMPILER=g++-6
  - BUILD_TYPE=Release COMPILER=clang++-3.9
  - BUILD_TYPE=Debug COMPILER=g++-4.9
  - BUILD_TYPE=Debug COMPILER=g++-5
  - BUILD_TYPE=Debug COMPILER=g++-6
  - BUILD_TYPE=Debug COMPILER=clang++-3.9
#  - BUILD_TYPE=Debug COMPILER=clang++-4.0
#  - BUILD_TYPE=Release COMPILER=clang++-4.0


addons:
  apt:
  sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-3.9
  packages:
    - g++-4.9
    - g++-5
    - g++-6
    - clang-3.9

#    - clang-4.0
#    - llvm-toolchain-trusty-4.0